/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import com.fazecast.jSerialComm.SerialPort;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author joao_
 */
public class CLPInterface extends javax.swing.JFrame {
    
    private String S1Expression;
    private String S2Expression;
    private String S3Expression;
    private String S4Expression;
    private String S5Expression;
    private String S6Expression;
    private String S7Expression;
    private String S8Expression;
    
    private String S1ExpressionValues;
    private String S2ExpressionValues;
    private String S3ExpressionValues;
    private String S4ExpressionValues;
    private String S5ExpressionValues;
    private String S6ExpressionValues;
    private String S7ExpressionValues;
    private String S8ExpressionValues;
    
    private String S1Value;
    private String S2Value;
    private String S3Value;
    private String S4Value;
    private String S5Value;
    private String S6Value;
    private String S7Value;
    private String S8Value;
    
    private String E1Value;
    private String E2Value;
    private String E3Value;
    private String E4Value;
    private String E5Value;
    private String E6Value;
    private String E7Value;
    private String E8Value;
        
    public CLPInterface() {
        initComponents();
        
        this.S1Value = "0";
        this.S2Value = "0";
        this.S3Value = "0";
        this.S4Value = "0";
        this.S5Value = "0";
        this.S6Value = "0";
        this.S7Value = "0";
        this.S8Value = "0";
        
        this.E1Value = "0";
        this.E2Value = "0";
        this.E3Value = "0";
        this.E4Value = "0";
        this.E5Value = "0";
        this.E6Value = "0";
        this.E7Value = "0";
        this.E8Value = "0";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        expressaoS1 = new javax.swing.JTextField();
        expressaoS2 = new javax.swing.JTextField();
        expressaoS3 = new javax.swing.JTextField();
        expressaoS4 = new javax.swing.JTextField();
        expressaoS5 = new javax.swing.JTextField();
        expressaoS6 = new javax.swing.JTextField();
        expressaoS7 = new javax.swing.JTextField();
        expressaoS8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        limparButton = new javax.swing.JButton();
        pararButton = new javax.swing.JButton();
        InicializarButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        expressaoS9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        expressaoS10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        expressaoS11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        expressaoS12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        expressaoS13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        expressaoS14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        expressaoS15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        expressaoS16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        expressaoS17 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        expressaoS18 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        expressaoS19 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        expressaoS20 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        expressaoS21 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        expressaoS22 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        expressaoS23 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        expressaoS24 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        valE1 = new javax.swing.JTextField();
        valE2 = new javax.swing.JTextField();
        valE3 = new javax.swing.JTextField();
        valE4 = new javax.swing.JTextField();
        valE5 = new javax.swing.JTextField();
        valE6 = new javax.swing.JTextField();
        valE7 = new javax.swing.JTextField();
        valE8 = new javax.swing.JTextField();
        valS1 = new javax.swing.JTextField();
        valS2 = new javax.swing.JTextField();
        valS3 = new javax.swing.JTextField();
        valS4 = new javax.swing.JTextField();
        valS5 = new javax.swing.JTextField();
        valS6 = new javax.swing.JTextField();
        valS7 = new javax.swing.JTextField();
        valS8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        expressaoS25 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        expressaoS26 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        expressaoS27 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        expressaoS28 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        expressaoS29 = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTROLADOR LÓGICO PROGRAMÁVEL");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite as expressões booleanas");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Saída 1:");

        expressaoS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Saída 2:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Saída 4:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Saída 3:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Saída 7:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Saída 8:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Saída 5:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Saída 6:");

        limparButton.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        limparButton.setText("LIMPAR");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        pararButton.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        pararButton.setText("PARAR");
        pararButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararButtonActionPerformed(evt);
            }
        });

        InicializarButton.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        InicializarButton.setText("INICIALIZAR");
        InicializarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicializarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(expressaoS4)
                                    .addComponent(expressaoS6)
                                    .addComponent(expressaoS5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expressaoS8)
                                    .addComponent(expressaoS7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expressaoS1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expressaoS2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expressaoS3, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(limparButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pararButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InicializarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(expressaoS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressaoS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressaoS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expressaoS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressaoS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressaoS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressaoS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressaoS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InicializarButton)
                    .addComponent(pararButton)
                    .addComponent(limparButton))
                .addGap(14, 14, 14))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VARIÁVEIS:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Entrada 1:");

        expressaoS9.setEditable(false);
        expressaoS9.setText("E1");
        expressaoS9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS9ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Entrada 2:");

        expressaoS10.setEditable(false);
        expressaoS10.setText("E2");
        expressaoS10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS10ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Entrada 3:");

        expressaoS11.setEditable(false);
        expressaoS11.setText("E3");
        expressaoS11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS11ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Entrada 4:");

        expressaoS12.setEditable(false);
        expressaoS12.setText("E4");
        expressaoS12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS12ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Entrada 5:");

        expressaoS13.setEditable(false);
        expressaoS13.setText("E5");
        expressaoS13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS13ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("Entrada 6:");

        expressaoS14.setEditable(false);
        expressaoS14.setText("E6");
        expressaoS14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS14ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("Entrada 7:");

        expressaoS15.setEditable(false);
        expressaoS15.setText("E7");
        expressaoS15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS15ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setText("Entrada 8:");

        expressaoS16.setEditable(false);
        expressaoS16.setText("E8");
        expressaoS16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS16ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setText("Saída 1:");

        expressaoS17.setEditable(false);
        expressaoS17.setText("S1");
        expressaoS17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS17ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("Saída 2:");

        expressaoS18.setEditable(false);
        expressaoS18.setText("S2");
        expressaoS18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS18ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setText("Saída 3:");

        expressaoS19.setEditable(false);
        expressaoS19.setText("S3");
        expressaoS19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS19ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setText("Saída 4:");

        expressaoS20.setEditable(false);
        expressaoS20.setText("S4");
        expressaoS20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS20ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setText("Saída 5:");

        expressaoS21.setEditable(false);
        expressaoS21.setText("S5");
        expressaoS21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS21ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel25.setText("Saída 6:");

        expressaoS22.setEditable(false);
        expressaoS22.setText("S6");
        expressaoS22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS22ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setText("Saída 7:");

        expressaoS23.setEditable(false);
        expressaoS23.setText("S7");
        expressaoS23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS23ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel27.setText("Saída 8:");

        expressaoS24.setEditable(false);
        expressaoS24.setText("S8");
        expressaoS24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS24ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Valores");

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Nomes");

        valE1.setEditable(false);
        valE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE1ActionPerformed(evt);
            }
        });

        valE2.setEditable(false);
        valE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE2ActionPerformed(evt);
            }
        });

        valE3.setEditable(false);
        valE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE3ActionPerformed(evt);
            }
        });

        valE4.setEditable(false);
        valE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE4ActionPerformed(evt);
            }
        });

        valE5.setEditable(false);
        valE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE5ActionPerformed(evt);
            }
        });

        valE6.setEditable(false);
        valE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE6ActionPerformed(evt);
            }
        });

        valE7.setEditable(false);
        valE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE7ActionPerformed(evt);
            }
        });

        valE8.setEditable(false);
        valE8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valE8ActionPerformed(evt);
            }
        });

        valS1.setEditable(false);
        valS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS1ActionPerformed(evt);
            }
        });

        valS2.setEditable(false);
        valS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS2ActionPerformed(evt);
            }
        });

        valS3.setEditable(false);
        valS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS3ActionPerformed(evt);
            }
        });

        valS4.setEditable(false);
        valS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS4ActionPerformed(evt);
            }
        });

        valS5.setEditable(false);
        valS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS5ActionPerformed(evt);
            }
        });

        valS6.setEditable(false);
        valS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS6ActionPerformed(evt);
            }
        });

        valS7.setEditable(false);
        valS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS7ActionPerformed(evt);
            }
        });

        valS8.setEditable(false);
        valS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valS8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(expressaoS9)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS24, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS23))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS22))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS21))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS20))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS19))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS18))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS17))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS16))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS15))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS14))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS13))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS12))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS11))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(expressaoS10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valE3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(valE2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(valE1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(valS7)
                    .addComponent(valS6)
                    .addComponent(valS5)
                    .addComponent(valS4)
                    .addComponent(valS3)
                    .addComponent(valS2)
                    .addComponent(valS1)
                    .addComponent(valE8)
                    .addComponent(valE7)
                    .addComponent(valE6)
                    .addComponent(valE5)
                    .addComponent(valE4)
                    .addComponent(valS8, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(expressaoS9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(expressaoS10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(expressaoS11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(expressaoS12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(expressaoS13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(expressaoS14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(expressaoS15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(expressaoS16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(expressaoS17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(expressaoS18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(expressaoS19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(expressaoS20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(expressaoS21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(expressaoS22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(expressaoS23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(expressaoS24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(valE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valE5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valE6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valE7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valE8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valS8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Sintaxe do CLP");

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel29.setText("Operação AND:");

        expressaoS25.setEditable(false);
        expressaoS25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        expressaoS25.setText("Expressão&&Expressão");
        expressaoS25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS25ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel30.setText("Operação OR:");

        expressaoS26.setEditable(false);
        expressaoS26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        expressaoS26.setText("Expressão||Expressão");
        expressaoS26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS26ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel31.setText("Operação NOT:");

        expressaoS27.setEditable(false);
        expressaoS27.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        expressaoS27.setText("!Expressão");
        expressaoS27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS27ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel32.setText("Procedência de operação:");

        expressaoS28.setEditable(false);
        expressaoS28.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        expressaoS28.setText("(Expressão)");
        expressaoS28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS28ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel33.setText("Exemplo de expressão:");

        expressaoS29.setEditable(false);
        expressaoS29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        expressaoS29.setText("!E1&&(E2||!(E4&&E7))");
        expressaoS29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressaoS29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expressaoS29)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(expressaoS27, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(expressaoS26, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(expressaoS25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(expressaoS28, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(expressaoS28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(expressaoS25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(expressaoS26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(expressaoS27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(expressaoS29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expressaoS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS1ActionPerformed

    private void pararButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararButtonActionPerformed
        valE1.setText("");
        valE1.setText("");
        valE1.setText("");
        valE1.setText("");
        valE1.setText("");
        valE1.setText("");
        valE1.setText("");
        valE1.setText("");
        valS1.setText("");
        valS1.setText("");
        valS1.setText("");
        valS1.setText("");
        valS1.setText("");
        valS1.setText("");
        valS1.setText("");
        valS1.setText("");
        
        
        
    }//GEN-LAST:event_pararButtonActionPerformed

    private void expressaoS9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS9ActionPerformed

    private void expressaoS10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS10ActionPerformed

    private void expressaoS11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS11ActionPerformed

    private void expressaoS12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS12ActionPerformed

    private void expressaoS13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS13ActionPerformed

    private void expressaoS14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS14ActionPerformed

    private void expressaoS15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS15ActionPerformed

    private void expressaoS16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS16ActionPerformed

    private void expressaoS17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS17ActionPerformed

    private void expressaoS18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS18ActionPerformed

    private void expressaoS19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS19ActionPerformed

    private void expressaoS20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS20ActionPerformed

    private void expressaoS21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS21ActionPerformed

    private void expressaoS22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS22ActionPerformed

    private void expressaoS23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS23ActionPerformed

    private void expressaoS24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS24ActionPerformed

    private void expressaoS25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS25ActionPerformed

    private void expressaoS26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS26ActionPerformed

    private void expressaoS27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS27ActionPerformed

    private void expressaoS28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS28ActionPerformed

    private void expressaoS29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressaoS29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressaoS29ActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        expressaoS1.setText("");
        expressaoS2.setText("");
        expressaoS3.setText("");
        expressaoS4.setText("");
        expressaoS5.setText("");
        expressaoS6.setText("");
        expressaoS7.setText("");
        expressaoS8.setText("");
    }//GEN-LAST:event_limparButtonActionPerformed

    private void InicializarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicializarButtonActionPerformed

        ScriptEngineManager sem = new ScriptEngineManager();
        ScriptEngine se = sem.getEngineByName("JavaScript");
            
        String[] arrayExpressions = {
            expressaoS1.getText(),
            expressaoS2.getText(),
            expressaoS3.getText(),
            expressaoS4.getText(),
            expressaoS5.getText(),
            expressaoS6.getText(),
            expressaoS7.getText(),
            expressaoS8.getText()
        };
        
        int[] arrayOutputValues = new int[8];
        
        SerialPort arduino = SerialPort.getCommPorts()[0];
        arduino.openPort();
        
        OutputStream out = arduino.getOutputStream();
        
        
        //arduino.closePort();
        
        InputStream comPortInput = arduino.getInputStream();
        //OutputStream comPortOutput = arduino.getOutputStream();
        
        
        Thread t = new Thread(){
            @Override
            public void run() {
                
                while (true) {  
                    try {
                        
                        //Scanner sc = new Scanner(System.in);
                        comPortInput.skip(comPortInput.available());
                        int readOneByASCII;
                        String phrase = "";
                        do{
                            readOneByASCII = comPortInput.read();
                            char letraEscrita = (char)readOneByASCII;
                            phrase = phrase+letraEscrita;
                        }while(readOneByASCII != 10);
                        System.out.println(phrase);
                        
                        if(phrase.charAt(0) == 'z' && phrase.endsWith("\n")){
                             /* 
                            zE1=0
                            E2=1
                            E3=1
                            E4=0
                            E5=1
                            E6=0
                            E7=0
                            E8=1
                            */
                            String[] splitphrase = phrase.split(";");
                            //String firstIndex = splitphrase[0].split("/")[1];

                            char[] arrayChar = new char[8];
                            arrayChar[0] = splitphrase[0].charAt(4);

                            for(int i=1; i<8; i++){
                                arrayChar[i] = splitphrase[i].charAt(3);
                            }
                            
                            String outputsStates = "Y";
                            
                            for(int i=0; i<8; i++){
                                for(int j=0; j<8; j++){
                                    arrayExpressions[i] = arrayExpressions[i].replace(String.format("E%d", j+1), String.valueOf(arrayChar[j]));
                                }
                                arrayOutputValues[i] = (int)se.eval(arrayExpressions[i]);
                                outputsStates = outputsStates.concat(String.format("S%d=%d;", i+1, arrayOutputValues[i]));
                                //out.write(String.format("yS%d=%d;", i+1, arrayOutputValues[i]).getBytes());
                                System.out.println(arrayOutputValues[i]);
                            }
                            outputsStates = outputsStates.concat("b\n");
                            System.out.println(outputsStates);
                            out.write(outputsStates.getBytes());
                            //...E1=0;E2=1;E3=1;E4=0;E5=1;E6=0;E7=0;E8=1;.
                            //..E1=0;E2=1;E3=1;E4=0;E5=1;E6=0;E7=0;E8=1;
                            //.E1=0;E2=1;E3=1;E4=0;E5=1;E6=0;E7=0;E8=1;
                            //E1=0;E2=1;E3=1;E4=0;E5=1;E6=0;E7=0;E8=1;.
                                           
                            valE1.setText(String.valueOf(arrayChar[0]));
                            valE2.setText(String.valueOf(arrayChar[1]));
                            valE3.setText(String.valueOf(arrayChar[2]));
                            valE4.setText(String.valueOf(arrayChar[3]));
                            valE5.setText(String.valueOf(arrayChar[4]));
                            valE6.setText(String.valueOf(arrayChar[5]));
                            valE7.setText(String.valueOf(arrayChar[6]));
                            valE8.setText(String.valueOf(arrayChar[7]));
                            valS1.setText(String.valueOf(arrayOutputValues[0]));
                            valS2.setText(String.valueOf(arrayOutputValues[1]));
                            valS3.setText(String.valueOf(arrayOutputValues[2]));
                            valS4.setText(String.valueOf(arrayOutputValues[3]));
                            valS5.setText(String.valueOf(arrayOutputValues[4]));
                            valS6.setText(String.valueOf(arrayOutputValues[5]));
                            valS7.setText(String.valueOf(arrayOutputValues[6]));
                            valS8.setText(String.valueOf(arrayOutputValues[7]));
                            }
                        
                    } catch (IOException ex) {
                        Logger.getLogger(CLPInterface.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ScriptException ex) {
                        Logger.getLogger(CLPInterface.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }          
        };
        t.start();
    }//GEN-LAST:event_InicializarButtonActionPerformed

    private void valE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE1ActionPerformed

    private void valE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE2ActionPerformed

    private void valE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE3ActionPerformed

    private void valE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE4ActionPerformed

    private void valE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE5ActionPerformed

    private void valE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE6ActionPerformed

    private void valE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE7ActionPerformed

    private void valE8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valE8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valE8ActionPerformed

    private void valS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS1ActionPerformed

    private void valS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS2ActionPerformed

    private void valS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS3ActionPerformed

    private void valS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS4ActionPerformed

    private void valS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS5ActionPerformed

    private void valS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS6ActionPerformed

    private void valS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS7ActionPerformed

    private void valS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valS8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valS8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLPInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLPInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InicializarButton;
    private javax.swing.JTextField expressaoS1;
    private javax.swing.JTextField expressaoS10;
    private javax.swing.JTextField expressaoS11;
    private javax.swing.JTextField expressaoS12;
    private javax.swing.JTextField expressaoS13;
    private javax.swing.JTextField expressaoS14;
    private javax.swing.JTextField expressaoS15;
    private javax.swing.JTextField expressaoS16;
    private javax.swing.JTextField expressaoS17;
    private javax.swing.JTextField expressaoS18;
    private javax.swing.JTextField expressaoS19;
    private javax.swing.JTextField expressaoS2;
    private javax.swing.JTextField expressaoS20;
    private javax.swing.JTextField expressaoS21;
    private javax.swing.JTextField expressaoS22;
    private javax.swing.JTextField expressaoS23;
    private javax.swing.JTextField expressaoS24;
    private javax.swing.JTextField expressaoS25;
    private javax.swing.JTextField expressaoS26;
    private javax.swing.JTextField expressaoS27;
    private javax.swing.JTextField expressaoS28;
    private javax.swing.JTextField expressaoS29;
    private javax.swing.JTextField expressaoS3;
    private javax.swing.JTextField expressaoS4;
    private javax.swing.JTextField expressaoS5;
    private javax.swing.JTextField expressaoS6;
    private javax.swing.JTextField expressaoS7;
    private javax.swing.JTextField expressaoS8;
    private javax.swing.JTextField expressaoS9;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton pararButton;
    private javax.swing.JTextField valE1;
    private javax.swing.JTextField valE2;
    private javax.swing.JTextField valE3;
    private javax.swing.JTextField valE4;
    private javax.swing.JTextField valE5;
    private javax.swing.JTextField valE6;
    private javax.swing.JTextField valE7;
    private javax.swing.JTextField valE8;
    private javax.swing.JTextField valS1;
    private javax.swing.JTextField valS2;
    private javax.swing.JTextField valS3;
    private javax.swing.JTextField valS4;
    private javax.swing.JTextField valS5;
    private javax.swing.JTextField valS6;
    private javax.swing.JTextField valS7;
    private javax.swing.JTextField valS8;
    // End of variables declaration//GEN-END:variables
}
